name: CD - Publish for Blazor / FluentUI

on:
  workflow_dispatch

jobs:
  publish:
    name: setup, build, validate, and publish
    runs-on: ubuntu-latest
    if: contains('nicholasrice,awentzel,eisenbergeffect', github.actor)

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        #VERSION_STATIC: 0.0.2
        TAG_FORMAT: v*

        
